---
# tasks file for ec2
 - name: Launch the instance
   ec2:
     key_name: "{{ key_name }}"
     instance_type: "{{ instance_type }}"
     image: "{{ ami }}"
     group: "{{ security_group }}"
     vpc_subnet_id: "{{ subnet_id }}"
     assign_public_ip: yes
     wait: true
     region: "{{ region }}"
     count: "{{count}}"
     aws_access_key: "{{access_key}}"
     aws_secret_key: "{{secret_access_key}}"
     instance_tags:
         Name: "{{tag_name}}"
   register: ec2

